# Generated by Django 4.2.7 on 2024-02-21 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_evento_usuario_alter_evento_data_evento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
